String.toLocaleString({

	"it": {
    "game-intro"           : "Join the <strong>FOR YOU BUBA!</strong>",
    "restart-button"       : "Play Again",
    "keep-playing-button"  : "Keep going",
    "retry-button"         : "Retry",
    "game-won"             : "You win!",
    "game-over"            : "Game over!",
    "game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
   
    "tweet1"               : "I scored \"",
    "tweet2"               : " at 2048-ForMriam #2048game",
    "tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '2'                    : 'first time',
    '4'                    : 'mimosa time',
    '8'                    : 'pool party',
    '16'                   : 'met gala',
    '32'                   : 'mr. and mrs.smith',
    '64'                   : 'taken from the back',
    '128'                  : 'banger',
    '256'                  : 'kissing with passion',
    '512'                  : 'autum and eve',
    '1024'                 : 'banger with a smile',
    '2048'                 : 'i love you buba',
    '4096'                 : 'wrestling with air',
    '8192'                 : 'better then life',
    'p0'                   : 'first time',
    'p4'                   : 'mimosa time',
    'p8'                   : 'pool party',
    'p16'                  : 'met gala',
    'p32'                  : 'mr. and mrs.smith',
    'p64'                  : 'taken from the back',
    'p128'                 : 'banger',
    'p256'                 : 'kissing with passion',
    'p512'                 : 'autum and eve',
    'p1024'                : 'banger with a smile',
    'p2048'                : 'i love you buba',
    'p4096'                : 'wrestling with air',
    'p8192'                : 'better then life',

	},

  "en": {
    "game-intro"           : "Join the <strong>For YOU BUBA!</strong>",
    "restart-button"       : "Play Again",
    "keep-playing-button"  : "Keep going",
    "retry-button"         : "Retry",
    "game-won"             : "You win!",
    "game-over"            : "Game over!",
    "game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\https://jsmith244.github.io/ForMiriam/">git.io/ForMiriamS</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "tweet1"               : "I scored \"",
    "tweet2"               : " at 2048-ForMriam #2048game"",
    "tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '2'                    : 'first time',
    '4'                    : 'mimosa time',
    '8'                    : 'pool party',
    '16'                   : 'met gala',
    '32'                   : 'mr. and mrs.smith',
    '64'                   : 'taken from the back',
    '128'                  : 'banger',
    '256'                  : 'kissing with passion',
    '512'                  : 'autum and eve',
    '1024'                 : 'banger with a smile',
    '2048'                 : 'i love you buba',
    '4096'                 : 'wrestling with air',
    '8192'                 : 'better then life',
    'p0'                   : 'first time',
    'p4'                   : 'mimosa time',
    'p8'                   : 'pool party',
    'p16'                  : 'met gala',
    'p32'                  : 'mr. and mrs.smith',
    'p64'                  : 'taken from the back',
    'p128'                 : 'banger',
    'p256'                 : 'kissing with passion',
    'p512'                 : 'autum and eve',
    'p1024'                : 'banger with a smile',
    'p2048'                : 'i love you buba',
    'p4096'                : 'wrestling with air',
    'p8192'                : 'better then life',
  }

});
